;;;; cd.asd
;;;;
;;;; Two systems, down from the twelve .asd files this repository carried at
;;;; its root (cd, cd-cffi, cd-all, cd-im, cd-im-cffi, cd-gl, cd-gl-cffi,
;;;; cd-pdf, cd-pdf-cffi, cd-context-plus, cd-context-plus-cffi, cd-examples).
;;;;
;;;; That layout paired every driver with its own -cffi system, but CD is a
;;;; single shared library: the drivers are compiled into libcd according to
;;;; CMake options, not shipped separately. There was never anything for the
;;;; extra systems to load independently.

(defsystem #:cd
  :description "Common Lisp bindings to CD, Tecgraf's Canvas Draw 2D graphics library."
  :author "Matthew Kennedy <burnsidemk@gmail.com>"
  :homepage "https://github.com/lispnik/cd"
  :licence "MIT"
  :version (:read-file-line "version.txt")
  :serial t
  :pathname "src"
  :components ((:file "package")
               (:file "conditions")
               (:file "library")
               ;; Generated by tools/gen-bindings.lisp, then hand-corrected.
               ;; types.lisp first: it defines the opaque handle types every
               ;; other file's signatures are written in terms of.
               (:module "ffi"
                :serial t
                :components ((:file "types")
                             (:file "cd")
                             (:file "cd-wd")
                             (:file "cd-image")
                             (:file "cd-im")
                             (:file "cd-svg")
                             (:file "cd-ps")
                             (:file "cd-pdf")
                             (:file "cd-cgm")
                             (:file "cd-dxf")
                             (:file "cd-dgn")
                             (:file "cd-mf")
                             (:file "cd-picture")
                             (:file "cd-debug")
                             (:file "cd-gl")
                             (:file "cd-native")
                             (:file "cd-clipboard")
                             (:file "cd-dbuffer")
                             (:file "cd-irgb")
                             (:file "cd-print")
                             (:file "cd-quartz")
                             (:file "manifest")))
               (:file "canvas")
               (:file "color")
               (:file "drawing")
               (:file "clipping")
               (:file "world")
               (:file "image")
               (:file "im")
               (:file "play"))
  ;; IM is a hard dependency, not an optional add-on: libcd here is built
  ;; against libim for the cdim driver, and the bridge in src/im.lisp takes
  ;; and returns the IM binding's image objects.
  :depends-on (#:cffi #:alexandria #:trivial-garbage #:im)
  :in-order-to ((test-op (test-op #:cd/tests))))

(defsystem #:cd/tests
  :description "FiveAM suite for the CD bindings."
  :author "Matthew Kennedy <burnsidemk@gmail.com>"
  :licence "MIT"
  :serial t
  :pathname "tests"
  :components ((:file "package")
               (:file "drawing")
               (:file "image"))
  :depends-on (#:cd #:fiveam #:trivial-garbage)
  ;; FiveAM's RUN! prints its report and returns NIL when anything failed;
  ;; discarding that makes TEST-OP succeed on a failing suite.
  :perform (test-op (op c)
                    (unless (uiop:symbol-call :fiveam :run!
                                              (uiop:find-symbol* :cd-suite :cd.tests))
                      (cl:error "The CD test suite failed."))))
