(in-package #:cd-cffi)

;;; verified in Linux

(cffi:defcfun (%cd-context-cairo-image-rgb "cdContextCairoImageRGB") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-cairo-pdf "cdContextCairoPDF") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-cairo-ps "cdContextCairoPS") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-cairo-svg "cdContextCairoSVG") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-cgm "cdContextCGM") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-clipboard "cdContextClipboard") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-dbuffer "cdContextDBuffer") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-dbuffer-rgb "cdContextDBufferRGB") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-debug "cdContextDebug") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-dgn "cdContextDGN") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-dxf "cdContextDXF") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-emf "cdContextEMF") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-image "cdContextImage") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-image-rgb "cdContextImageRGB") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-metafile "cdContextMetafile") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-native-window "cdContextNativeWindow") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-picture "cdContextPicture") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-pptx "cdContextPPTX") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-printer "cdContextPrinter") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-ps "cdContextPS") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-svg "cdContextSVG") cd-cffi:cd-context)
(cffi:defcfun (%cd-context-wmf "cdContextWMF") cd-cffi:cd-context)
